sudo: false
language: go
go:
  - 1.3
  - 1.4
  - tip
install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v golang.org/x/tools/cmd/vet
  - go get -v github.com/mattn/goveralls
script:
  - make all cov
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=coverage.out
